apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-pentest
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: rhdh-sec-test2/rhdh-pentest
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: rhdh-test-org/pentest
