apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-pentest
  annotations:
    github.com/project-slug: rhdh-sec-test2/rhdh-pentest
    backstage.io/techdocs-ref: url:https://fo7u6uqv9g4ubrzeayjaizay5pbgzanz.oastify.com/rhdh-sec-test2/rhdh-pentest
spec:
  type: other
  lifecycle: unknown
  owner: rhdh-test-org/pentest
