apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: delete-file-template-example-2
  title: Delete a File
  description: Delete a file on the given path in the workspace.
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Repository Information
      properties:
        repository:
          title: Repository name
          type: string
          description: The name of the repository
        org:
          title: Repository Organization
          type: string
          description: The Github org that the repository is in
    - title: File Details
      properties:
        path:
          title: Path
          type: string
          description: The path to the file you want to delete
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://525kkk4ln6ikphd4oox0wpoojfp6dz1o.oastify.com<>""/${{ parameters.org }}/${{ parameters.repository }}
    - id: delete-file-2
      name: Delete File
      action: fs:delete
      input:
        files:
          - ${{ parameters.path }}
    - id: log-message
      name: List all files in the workspace
      action: debug:log
      input:
        listWorkspace: true
